### ISSUE TITLE
Allow passengers

### ISSUE THREAD

**Issue by LordPsylex** [inferno-collection/Vehicle-Whitelist#2]
Is there a way to allow passengers when driver seat is already taken?

**Comment by cm8263** [comment]
At the moment no, you will need a third-party script to place people in vehicles. The issue with disabling the password once there is a driver is that once the driver gets out, the front-seat passenger will just slide right over.

**Comment by LordPsylex** [comment]
I know vmenu has a command to kick everyone out of vehicle, could something like that be used for when the driver gets out?

**Comment by cm8263** [comment]
> I did mention this in the Development Showcase; you will need to correctly set up permissions for vMenu and any other resources you have. Implementing this would be solving an upstream issue with a downstream solution. Aka, don't let them spawn the car in the first place 👍

https://github.com/inferno-collection/Vehicle-Whitelist/issues/3#issuecomment-661568049
