### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by LordPsylex** [inferno-collection/Vehicle-Whitelist#3]
Kick player out if not allowed to drive

When people spawn the car, they can drive it until they get out and then they cant get back in, however some people would just spawn another car and bypass this. Is there away to make it so if they spawn the vehicle they instantly get kicked out of said vehicle?

**Comment by cm8263** [comment]
I did mention this in the Development Showcase; you will need to correctly set up permissions for vMenu and any other resources you have. Implementing this would be solving an upstream issue with a downstream solution. Aka, don't let them spawn the car in the first place 👍
